<a href="https://colab.research.google.com/github/AvinashB-DA/Robot-Programming-Labs/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 01  NumPy Library

**Student ID : 202201211 Name : Baraiya Avinash**

**Student ID : 202201143 Name : Vegad Rutvik**



In [1]:
import numpy as np


# Creating a 1D array

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# Creating a 2D array

In [3]:
arr_2d = np.array([[1, 2, 3],[ 4, 5, 6]])
print(arr_2d)


[[1 2 3]
 [4 5 6]]


# Array attributes: shape, dimesnions, size and data type
## arr.shape  Returns the shape of the array
## arr.ndim   Returns the number of dimensions
## arr.size   Returns the total number of elements
## arr.dtype # Returns the data type of elements

In [4]:
print(arr_2d.shape)

(2, 3)


In [5]:
print(arr_2d.ndim)

2


In [6]:
arr.size

5

In [7]:
arr.dtype

dtype('int64')

# Array indexing and slicing

In [8]:
# print all elements second onwards

In [9]:
print(arr_2d[1,2])
print(arr_2d[0:2, 1:3])

6
[[2 3]
 [5 6]]


In [10]:
# print elements in arr_2d: first three rows and second to fourth column

# Universal functions

In [11]:
np.sqrt(arr)
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

# aggregation functions

In [12]:
mean = np.mean(arr)
std = np.std(arr)
arr_max = np.max(arr)


In [13]:
print(f"Array is {arr}", f"; Mean is {mean}", f"std. deviation is {std}", f"Max value is {arr_max}" )

Array is [1 2 3 4 5] ; Mean is 3.0 std. deviation is 1.4142135623730951 Max value is 5


# Linear Algebra
## DOt product


In [14]:
np.dot(arr, arr)

55

## Matrix Multiplication

In [15]:
matrix1 = np.array([ [1,2],[3,4]])
matrix2 = np.array([ [5,6],[7,8]])
np.matmul(matrix1, matrix2)

array([[19, 22],
       [43, 50]])

## Eigenvalues and EIgendecomposition

In [16]:
eigenvalues, eigenvectors = np.linalg.eig(matrix1)

In [17]:
print(eigenvalues, eigenvectors)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Random Number Generation

In [18]:
np.random.rand(5) # array of 5 random numbers between 0 and 1

array([0.14293582, 0.12247078, 0.43063866, 0.58142307, 0.51270712])

## Random Integers

In [19]:
np.random.randint(0, 10, size=5) #  array of 5 random integers between 0 and 10

array([2, 1, 3, 6, 2])

## Reshaping Arrays

In [20]:
arr = np.arange(12)
arr_reshaped = arr.reshape((1, 3, 4))  # Reshape to 3x4 array
print(arr)
print(arr_reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


## Flattening arrays

In [21]:
arr_flat = arr_reshaped.flatten()

In [22]:
print(arr_flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## Broadcasting

In [23]:
arr = np.array([1, 2, 3])
result = arr + np.array([10])  # Broadcasting the addition
print(result)

[11 12 13]


## Broadcatsing with a scalar

In [24]:
# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Add a scalar value to each element of the array
result = array + 10

print("Original Array:")
print(array)
print("\nArray after adding scalar 10:")
print(result)


Original Array:
[[1 2 3]
 [4 5 6]]

Array after adding scalar 10:
[[11 12 13]
 [14 15 16]]


## Broadcasting with different shaped arrays

In [25]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
array_1d = np.array([10, 20, 30])

# Add the 1D array to the 2D array
result = array_2d + array_1d

print("2D Array:")
print(array_2d)
print("\n1D Array:")
print(array_1d)
print("\nResult after broadcasting:")
print(result)


2D Array:
[[1 2 3]
 [4 5 6]]

1D Array:
[10 20 30]

Result after broadcasting:
[[11 22 33]
 [14 25 36]]


## Broadcasting with higher dimensions

In [26]:
# Create a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Create a 2D array
array_2d = np.array([[1, 0, 1]])

# Add the 2D array to the 3D array
result = array_3d + array_2d

print("3D Array:")
print(array_3d)
print("\n2D Array:")
print(array_2d)
print("\nResult after broadcasting:")
print(result)


3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

2D Array:
[[1 0 1]]

Result after broadcasting:
[[[ 2  2  4]
  [ 5  5  7]]

 [[ 8  8 10]
  [11 11 13]]]


In [27]:
print(array_3d.shape)

(2, 2, 3)


In [28]:
print(array_2d.shape)

(1, 3)


## Boolean Masking

In [29]:
import numpy as np
# Create a NumPy array of pixel intensities
intensities = np.array([0, 25, 19, 220, 100, 58, 9, 45, 90, 78, 56])

print("Original Array:")
print(intensities)

# Define the threshold
threshold = 25

# Create a boolean mask where the condition is intensities > threshold
mask = intensities > threshold

print("Boolean Mask:")
print(mask)

# Apply the boolean mask to the original array
filtered_intensities = intensities[mask]

print("Filtered intensities (Above Threshold):")
print(filtered_intensities)


Original Array:
[  0  25  19 220 100  58   9  45  90  78  56]
Boolean Mask:
[False False False  True  True  True False  True  True  True  True]
Filtered intensities (Above Threshold):
[220 100  58  45  90  78  56]
