<a href="https://colab.research.google.com/github/AvinashB-DA/Robot-Programming-Labs/blob/main/Lab01/Lab01_Q_1_to_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 01  Q- 1 to 9

**Group Name - Techno Titans**  

**Student ID : 202201211 Name : Baraiya Avinash**

**Student ID : 202201143 Name : Vegad Rutvik**



Q1. Write a function that gives number of days of given year.
Input : 1990 Input : 2044
Output : 365 Output : 366

In [1]:
def number_of_days(year):
    # Check if the year is a leap year
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return 366
    else:
        return 365

# Test the function
print(number_of_days(1990))  # Output: 365
print(number_of_days(2044))  # Output: 366

365
366


Q2. Count the frequency of each character in a string and store it in a dictionary. An example is given
below.
Input: ‘adcbbdaacd’ Output: {‘a’: 3, ‘b’: 2, ‘c’: 2, ‘d’: 3}

In [2]:
# Q2. Count the frequency of each character in a string and store it in a dictionary.
def char_frequency(s):
    freq = {}
    for char in s:
        if char in freq:
            freq[char] += 1
        else:
            freq[char] = 1
    return freq

# Test the function
print(char_frequency('adcbbdaacd'))  # Output: {'a': 3, 'd': 3, 'c': 2, 'b': 2}

{'a': 3, 'd': 3, 'c': 2, 'b': 2}


Q3. Write a program to remove duplicates from a list but keep the first
occurrence of each element.
Input: [1, 2, 3, 4, 2, 3, 5, 6, 1, 4]
Output: [1, 2, 3, 4, 5, 6]

In [3]:
def remove_duplicates(lst):
    seen = set()
    result = []
    for item in lst:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

# Test the function
input_list = [1, 2, 3, 4, 2, 3, 5, 6, 1, 4]
print(remove_duplicates(input_list))  # Output: [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]


Q4. Write a program to sort a stack using only another stack (no other data structures like arrays or
linked lists).
Input: stack = [9, 5, 1, 3]
Output: stack = [1, 3, 5, 9]

In [4]:
def sort_stack(input_stack):
    temp_stack = []

    while input_stack:
        # Pop an element from the input stack
        temp = input_stack.pop()

        # While temporary stack is not empty and top of temp_stack is greater than temp
        while temp_stack and temp_stack[-1] > temp:
            # Pop from temp_stack and push it to the input stack
            input_stack.append(temp_stack.pop())

        # Push temp in temp_stack
        temp_stack.append(temp)

    # Transfer sorted elements back to input_stack
    while temp_stack:
        input_stack.append(temp_stack.pop())

    return input_stack

# Test the function
stack = [9, 5, 1, 3]
sorted_stack = sort_stack(stack)
print(sorted_stack)  # Output: [1, 3, 5, 9]

[9, 5, 3, 1]


Q5. Make a module “pascal.py” with function “pascalTriangle(numOfRows)” and import into
“main.py”.
Input : Enter the num of rows : 7

In [5]:
def pascalTriangle(numOfRows):
    result = []
    for i in range(numOfRows):
        row = [1] * (i + 1)
        for j in range(1, i):
            row[j] = result[i - 1][j - 1] + result[i - 1][j]
        result.append(row)
    return result

pascalPrint = pascalTriangle(7)
for row in pascalPrint:
    print(' ' * (len(pascalPrint) - len(row)), end=' ')
    print(' '.join(map(str, row)))


       1
      1 1
     1 2 1
    1 3 3 1
   1 4 6 4 1
  1 5 10 10 5 1
 1 6 15 20 15 6 1


Q6. Create a 6x6 matrix with random values and:
Replace all values greater than 0.5 with 1, and all others with 0.
Extract a 3x3 submatrix starting from index (2, 2) and calculate its mean.

In [6]:
import numpy as np

# Create a 6x6 matrix with random values
matrix = np.random.rand(6, 6)
print("Original Matrix:\n", matrix)

# Replace all values greater than 0.5 with 1, and all others with 0
matrix[matrix > 0.5] = 1
matrix[matrix <= 0.5] = 0
print("Modified Matrix:\n", matrix)

# Extract a 3x3 submatrix starting from index (2, 2)
submatrix = matrix[2:5, 2:5]
print("3x3 Submatrix:\n", submatrix)

# Calculate the mean of the submatrix
mean_value = np.mean(submatrix)
print("Mean of the 3x3 Submatrix:", mean_value)

Original Matrix:
 [[0.86948825 0.08535051 0.03110924 0.65474528 0.31696023 0.90722825]
 [0.54964249 0.79003971 0.7535203  0.17362317 0.08825059 0.5329868 ]
 [0.65850493 0.65487526 0.38548826 0.75856598 0.10346746 0.18233795]
 [0.13527768 0.1331289  0.83916592 0.00684537 0.40230358 0.25530891]
 [0.47449244 0.91574933 0.59769771 0.69017271 0.98406469 0.22147995]
 [0.98047217 0.54919604 0.70142147 0.1340408  0.66148345 0.99676638]]
Modified Matrix:
 [[1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 1.]]
3x3 Submatrix:
 [[0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]]
Mean of the 3x3 Submatrix: 0.5555555555555556


Q7. Array Reshaping:
Create a 1D array with 16 elements. Reshape it into a 4x4 matrix.
Flatten a 3x3x3 array into a 1D array.
Reshape a matrix into a new shape without changing its data.

In [7]:
import numpy as np

# Create a 1D array with 16 elements
array_1d = np.arange(16)
print("\n\n1D Array:\n", array_1d)

# Reshape it into a 4x4 matrix
matrix_4x4 = array_1d.reshape(4, 4)
print("\n\n4x4 Matrix:\n", matrix_4x4)

# Create a 3x3x3 array
array_3x3x3 = np.arange(27).reshape(3, 3, 3)
print("\n\n3x3x3 Array:\n", array_3x3x3)

# Flatten the 3x3x3 array into a 1D array
flattened_array = array_3x3x3.flatten()
print("\n\nFlattened Array:\n", flattened_array)

# Reshape a matrix into a new shape without changing its data
reshaped_matrix = matrix_4x4.reshape(2, 8)
print("\n\nReshaped Matrix (2x8):\n", reshaped_matrix)



1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


4x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


3x3x3 Array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


Reshaped Matrix (2x8):
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


Q8. Write a recursive function Fibonacci_sum(n) to calaculate the sum of first n numbers in Fibonacci
series 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
Input: 1 Output: 0
Input: 4: Output: 4

In [8]:
def Fibonacci_sum(n):
    # Base cases
    if n <= 0:
        return 0
    elif n == 1:
        return 0
    elif n == 2:
        return 1
    else:
        # Recursive case
        return Fibonacci_sum(n-1)  + Fibonacci(n-1)

def Fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return Fibonacci(n-1) + Fibonacci(n-2)

# Test the function
print(Fibonacci_sum(1))  # Output: 0
print(Fibonacci_sum(4))  # Output: 4
print(Fibonacci_sum(7))  # Output: 20

0
4
20


Q9. Define a function get_value_from_dict that takes a dictionary and a key as parameters. If the key
is not present in the dictionary, the function should raise a KeyError with a custom error message.
Write a main function that calls get_value_from_dict with a dictionary and user-provided key. Handle
KeyError and display a user-friendly message if the key is not found.

In [9]:
def get_value_from_dict(d, key):
    if key not in d:
        raise KeyError(f"Key '{key}' not found in the dictionary.")
    return d[key]

def main():
    sample_dict = {
        'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10,
        'k': 11, 'l': 12
    }
    user_key = 'a'  # Static key

    try:
        value = get_value_from_dict(sample_dict, user_key)
        print(f"The value for key '{user_key}' is {value}.")
    except KeyError as e:
        print(e)

# Call the main function
main()

The value for key 'a' is 1.
